# Generated by Django 4.2.5 on 2023-09-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='prfile',
            new_name='profile',
        ),
    ]
