# Generated by Django 4.2.5 on 2023-09-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_booking_options_alter_amenity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprovado', 'Aprobado')], max_length=20, verbose_name='Estado'),
        ),
    ]
